language: python

python:
  - 3.7

os:
  - linux

cache: pip

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda

install:
  - conda env create -f environement.yml
  - pip install .

script:
  - pytest
