language: python

python:
    # sets TRAVIS_PYTHON_VERSION
    - 3.7

os:
    - linux
    # - osx   # currently osx python projects are not supported in Travis

cache: pip

install:
    - pip install -r requirements.txt
    - python setup.py install

script:
    - pytest 
