language: python

python:
  - 3.6
  - 3.7
  - 3.8

os:
  - linux

cache: pip

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  -	source $HOME/miniconda/etc/profile.d/conda.sh

install:
  - conda env create -f environement.yml
  - conda activate ctaplot
  - pip install .

script:
  - pytest
