language: python

python:
  - "3.5"
  - "3.6"
  
# command to install dependencies
install:

  # Install miniconda following instructions at
  # http://conda.pydata.org/docs/travis.html
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda  # get latest conda version
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create --name ctaplot python=$TRAVIS_PYTHON_VERSION
  - conda env update -n ctaplot --file environment.yml
  - source activate ctaplot
    
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
